In [2]:
import pandas as pd

df_metricas = pd.read_csv("data.csv", delimiter= ";", encoding="utf-8")
display(df_metricas)

,user,cpu_percent,cpu_frequency,ram_percent,swap_memory_total,swap_memory_used,swap_memory_percent,upload_speed,download_speed,temperature,fans_speed,disk,gpu_usage,gpu_energy,timestamp
0,9c:c7:d3:fe:61:5e,21.5,1.3,94.7,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:42:33.308688
1,9c:c7:d3:fe:61:5e,9.1,1.3,95.2,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:22.218620
2,9c:c7:d3:fe:61:5e,1.8,1.3,95.2,10.13,1.86,18.4,0.16,0.24,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:32.258389
3,9c:c7:d3:fe:61:5e,5.9,1.3,94.6,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:36.987173
4,9c:c7:d3:fe:61:5e,23.7,1.3,54.6,6.75,0.00,0.0,0.00,0.00,0.0,0.0,339.38,0.0,0.0,2026-09-20 09:45:40.882397

In [3]:
display(df_metricas.info())
#pegar dados (ver informações dos mesmos)

print(list(df_metricas.columns))

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   user                 5 non-null      str
 1   cpu_percent          5 non-null      float64
 2   cpu_frequency        5 non-null      float64
 3   ram_percent          5 non-null      float64
 4   swap_memory_total    5 non-null      float64
 5   swap_memory_used     5 non-null      float64
 6   swap_memory_percent  5 non-null      float64
 7   upload_speed         5 non-null      float64
 8   download_speed       5 non-null      float64
 9   temperature          5 non-null      float64
 10  fans_speed           5 non-null      float64
 11  disk                 5 non-null      float64
 12  gpu_usage            5 non-null      float64
 13  gpu_energy           5 non-null      float64
 14  timestamp            5 non-null      str
dtypes: float64(13), str(2)
memory usage: 732.0 bytes

None

['user', 'cpu_percent', 'cpu_frequency', 'ram_percent', 'swap_memory_total', 'swap_memory_used', 'swap_memory_percent', 'upload_speed', 'download_speed', 'temperature', 'fans_speed', 'disk', 'gpu_usage', 'gpu_energy', 'timestamp']

In [4]:
print(df_metricas["cpu_frequency"])

df_metricas_analisadas = df_metricas

df_metricas_analisadas["timestamp"] = pd.to_datetime(df_metricas_analisadas["timestamp"], format="%Y-%m-%d %H:%M:%S.%f")

0    1.3
1    1.3
2    1.3
3    1.3
4    1.3
Name: cpu_frequency, dtype: float64

In [5]:
df_metricas_analisadas["timestamp"].info()
#agora ta datetime

df_metricas_analisadas["user"] = df_metricas_analisadas["user"].str.upper()
df_metricas_analisadas["user"]

df_metricas_analisadas = df_metricas_analisadas.drop_duplicates(subset=["timestamp"], keep="first")

df_metricas_analisadas["timestamp"] = df_metricas_analisadas["timestamp"].dt.floor('s')

df_metricas_analisadas = df_metricas_analisadas.fillna(0)

display(df_metricas_analisadas)

<class 'pandas.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: timestamp
Non-Null Count  Dtype
--------------  -----
5 non-null      datetime64[us]
dtypes: datetime64[us](1)
memory usage: 172.0 bytes

,user,cpu_percent,cpu_frequency,ram_percent,swap_memory_total,swap_memory_used,swap_memory_percent,upload_speed,download_speed,temperature,fans_speed,disk,gpu_usage,gpu_energy,timestamp
0,9C:C7:D3:FE:61:5E,21.5,1.3,94.7,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:42:33
1,9C:C7:D3:FE:61:5E,9.1,1.3,95.2,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:22
2,9C:C7:D3:FE:61:5E,1.8,1.3,95.2,10.13,1.86,18.4,0.16,0.24,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:32
3,9C:C7:D3:FE:61:5E,5.9,1.3,94.6,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:36
4,9C:C7:D3:FE:61:5E,23.7,1.3,54.6,6.75,0.00,0.0,0.00,0.00,0.0,0.0,339.38,0.0,0.0,2026-09-20 09:45:40

In [6]:
display(df_metricas_analisadas)

,user,cpu_percent,cpu_frequency,ram_percent,swap_memory_total,swap_memory_used,swap_memory_percent,upload_speed,download_speed,temperature,fans_speed,disk,gpu_usage,gpu_energy,timestamp
0,9C:C7:D3:FE:61:5E,21.5,1.3,94.7,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:42:33
1,9C:C7:D3:FE:61:5E,9.1,1.3,95.2,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:22
2,9C:C7:D3:FE:61:5E,1.8,1.3,95.2,10.13,1.86,18.4,0.16,0.24,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:32
3,9C:C7:D3:FE:61:5E,5.9,1.3,94.6,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:36
4,9C:C7:D3:FE:61:5E,23.7,1.3,54.6,6.75,0.00,0.0,0.00,0.00,0.0,0.0,339.38,0.0,0.0,2026-09-20 09:45:40

In [7]:
print(df_metricas_analisadas["cpu_percent"].mean())
display(df_metricas_analisadas["cpu_percent"])
print(df_metricas_analisadas["cpu_percent"].max())

cpu_alta = df_metricas_analisadas[df_metricas_analisadas["ram_percent"] > 95.0]
display(cpu_alta)

display(cpu_alta["timestamp"].dt.day_name())
#as duas no sabado

12.4

0    21.5
1     9.1
2     1.8
3     5.9
4    23.7
Name: cpu_percent, dtype: float64

23.7

,user,cpu_percent,cpu_frequency,ram_percent,swap_memory_total,swap_memory_used,swap_memory_percent,upload_speed,download_speed,temperature,fans_speed,disk,gpu_usage,gpu_energy,timestamp
1,9C:C7:D3:FE:61:5E,9.1,1.3,95.2,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:22
2,9C:C7:D3:FE:61:5E,1.8,1.3,95.2,10.13,1.86,18.4,0.16,0.24,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:32

1    Saturday
2    Saturday
Name: timestamp, dtype: str

In [ ]:
#media por dia da semana
media_cpu_por_dia = df_metricas_analisadas.groupby(df_metricas_analisadas["timestamp"].dt.day_name())["cpu_percent"].mean()

display(media_cpu_por_dia)

dados_do_sabado = df_metricas_analisadas[df_metricas_analisadas["timestamp"].dt.weekday == 5]

print("media sabado")
print(dados_do_sabado["cpu_percent"].mean())

timestamp
Saturday     9.575
Sunday      23.700
Name: cpu_percent, dtype: float64

media sabado
9.575

In [ ]:

df_semtexto = df_metricas_analisadas.drop(columns=["user"])
ultima = df_semtexto["timestamp"].max()
uma_hora =  df_semtexto[df_semtexto["timestamp"] >= (ultima - pd.Timedelta(hours=1))]
um_dia =  df_semtexto[df_semtexto["timestamp"] >= (ultima - pd.Timedelta(hours=24))]

display(df_semtexto)

df_media_ultima_hora = uma_hora.groupby(uma_hora["timestamp"].dt.floor('h'), "user").mean()
df_media_ultimo_dia = um_dia.groupby(um_dia["timestamp"].dt.floor('h'), "user").mean()

display(df_media_ultima_hora)
display(df_media_ultimo_dia)

,cpu_percent,cpu_frequency,ram_percent,swap_memory_total,swap_memory_used,swap_memory_percent,upload_speed,download_speed,temperature,fans_speed,disk,gpu_usage,gpu_energy,timestamp
0,21.5,1.3,94.7,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:42:33
1,9.1,1.3,95.2,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:22
2,1.8,1.3,95.2,10.13,1.86,18.4,0.16,0.24,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:32
3,5.9,1.3,94.6,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:36
4,23.7,1.3,54.6,6.75,0.00,0.0,0.00,0.00,0.0,0.0,339.38,0.0,0.0,2026-09-20 09:45:40

,cpu_percent,cpu_frequency,ram_percent,swap_memory_total,swap_memory_used,swap_memory_percent,upload_speed,download_speed,temperature,fans_speed,disk,gpu_usage,gpu_energy,timestamp
timestamp,,,,,,,,,,,,,,
2026-09-20 09:00:00,23.7,1.3,54.6,6.75,0.0,0.0,0.0,0.0,0.0,0.0,339.38,0.0,0.0,2026-09-20 09:45:40

,cpu_percent,cpu_frequency,ram_percent,swap_memory_total,swap_memory_used,swap_memory_percent,upload_speed,download_speed,temperature,fans_speed,disk,gpu_usage,gpu_energy,timestamp
timestamp,,,,,,,,,,,,,,
2026-09-19 18:00:00,9.575,1.3,94.925,10.13,1.86,18.4,0.04,0.06,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:15.750
2026-09-20 09:00:00,23.700,1.3,54.600,6.75,0.00,0.0,0.00,0.00,0.0,0.0,339.38,0.0,0.0,2026-09-20 09:45:40.000