In [24]:
import pandas as pd

df_metricas = pd.read_csv("data.csv", delimiter= ";", encoding="utf-8")
display(df_metricas)

,user,cpu_percent,cpu_frequency,ram_percent,swap_memory_total,swap_memory_used,swap_memory_percent,upload_speed,download_speed,temperature,fans_speed,disk,gpu_usage,gpu_energy,timestamp
0,9c:c7:d3:fe:61:5e,21.5,1.3,94.7,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:42:33.308688
1,9c:c7:d3:fe:61:5e,9.1,1.3,95.2,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:22.218620
2,9c:c7:d3:fe:61:5e,1.8,1.3,95.2,10.13,1.86,18.4,0.16,0.24,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:32.258389
3,9c:c7:d3:fe:61:5e,5.9,1.3,94.6,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:36.987173
4,9c:c7:d3:fe:61:5e,23.7,1.3,54.6,6.75,0.00,0.0,0.00,0.00,0.0,0.0,339.38,0.0,0.0,2026-09-20 09:45:40.882397
5,9c:c7:d3:fe:61:5e,12.7,1.3,68.8,6.75,0.12,1.7,0.00,570.43,0.0,0.0,339.18,0.0,0.0,2026-09-20 12:19:07.016356
6,9c:c7:d3:fe:61:5e,8.5,1.3,68.7,6.75,0.12,1.7,0.08,0.14,0.0,0.0,339.18,0.0,0.0,2026-09-20 12:19:17.025804
7,9c:c7:d3:fe:61:5e,4.3,1.3,68.4,6.75,0.12,1.7,0.05,0.08,0.0,0.0,339.18,0.0,0.0,2026-09-20 12:19:27.040470
8,9c:c7:d3:fe:61:5e,3.1,1.3,68.5,6.75,0.11,1.7,0.03,0.02,0.0,0.0,339.18,0.0,0.0,2026-09-20 12:19:37.053380
9,9c:c7:d3:fe:61:5e,2.5,1.3,67.9,6.75,0.12,1.8,0.02,0.02,0.0,0.0,339.18,0.0,0.0,2026-09-20 12:19:47.068900

In [25]:
display(df_metricas.info())
#pegar dados (ver informações dos mesmos)

print(list(df_metricas.columns))

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   user                 10 non-null     str
 1   cpu_percent          10 non-null     float64
 2   cpu_frequency        10 non-null     float64
 3   ram_percent          10 non-null     float64
 4   swap_memory_total    10 non-null     float64
 5   swap_memory_used     10 non-null     float64
 6   swap_memory_percent  10 non-null     float64
 7   upload_speed         10 non-null     float64
 8   download_speed       10 non-null     float64
 9   temperature          10 non-null     float64
 10  fans_speed           10 non-null     float64
 11  disk                 10 non-null     float64
 12  gpu_usage            10 non-null     float64
 13  gpu_energy           10 non-null     float64
 14  timestamp            10 non-null     str
dtypes: float64(13), str(2)
memory usage: 1.3 KB

None

['user', 'cpu_percent', 'cpu_frequency', 'ram_percent', 'swap_memory_total', 'swap_memory_used', 'swap_memory_percent', 'upload_speed', 'download_speed', 'temperature', 'fans_speed', 'disk', 'gpu_usage', 'gpu_energy', 'timestamp']

In [26]:
print(df_metricas["cpu_frequency"])

df_metricas_analisadas = df_metricas

df_metricas_analisadas["timestamp"] = pd.to_datetime(df_metricas_analisadas["timestamp"], format="%Y-%m-%d %H:%M:%S.%f")

0    1.3
1    1.3
2    1.3
3    1.3
4    1.3
5    1.3
6    1.3
7    1.3
8    1.3
9    1.3
Name: cpu_frequency, dtype: float64

In [27]:
df_metricas_analisadas["timestamp"].info()
#agora ta datetime

df_metricas_analisadas["user"] = df_metricas_analisadas["user"].str.upper()
df_metricas_analisadas["user"]

df_metricas_analisadas = df_metricas_analisadas.drop_duplicates(subset=["timestamp"], keep="first")

df_metricas_analisadas["timestamp"] = df_metricas_analisadas["timestamp"].dt.floor('s')

df_metricas_analisadas = df_metricas_analisadas.fillna(0)

display(df_metricas_analisadas)

<class 'pandas.Series'>
RangeIndex: 10 entries, 0 to 9
Series name: timestamp
Non-Null Count  Dtype
--------------  -----
10 non-null     datetime64[us]
dtypes: datetime64[us](1)
memory usage: 212.0 bytes

,user,cpu_percent,cpu_frequency,ram_percent,swap_memory_total,swap_memory_used,swap_memory_percent,upload_speed,download_speed,temperature,fans_speed,disk,gpu_usage,gpu_energy,timestamp
0,9C:C7:D3:FE:61:5E,21.5,1.3,94.7,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:42:33
1,9C:C7:D3:FE:61:5E,9.1,1.3,95.2,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:22
2,9C:C7:D3:FE:61:5E,1.8,1.3,95.2,10.13,1.86,18.4,0.16,0.24,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:32
3,9C:C7:D3:FE:61:5E,5.9,1.3,94.6,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:36
4,9C:C7:D3:FE:61:5E,23.7,1.3,54.6,6.75,0.00,0.0,0.00,0.00,0.0,0.0,339.38,0.0,0.0,2026-09-20 09:45:40
5,9C:C7:D3:FE:61:5E,12.7,1.3,68.8,6.75,0.12,1.7,0.00,570.43,0.0,0.0,339.18,0.0,0.0,2026-09-20 12:19:07
6,9C:C7:D3:FE:61:5E,8.5,1.3,68.7,6.75,0.12,1.7,0.08,0.14,0.0,0.0,339.18,0.0,0.0,2026-09-20 12:19:17
7,9C:C7:D3:FE:61:5E,4.3,1.3,68.4,6.75,0.12,1.7,0.05,0.08,0.0,0.0,339.18,0.0,0.0,2026-09-20 12:19:27
8,9C:C7:D3:FE:61:5E,3.1,1.3,68.5,6.75,0.11,1.7,0.03,0.02,0.0,0.0,339.18,0.0,0.0,2026-09-20 12:19:37
9,9C:C7:D3:FE:61:5E,2.5,1.3,67.9,6.75,0.12,1.8,0.02,0.02,0.0,0.0,339.18,0.0,0.0,2026-09-20 12:19:47

In [28]:
display(df_metricas_analisadas)

,user,cpu_percent,cpu_frequency,ram_percent,swap_memory_total,swap_memory_used,swap_memory_percent,upload_speed,download_speed,temperature,fans_speed,disk,gpu_usage,gpu_energy,timestamp
0,9C:C7:D3:FE:61:5E,21.5,1.3,94.7,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:42:33
1,9C:C7:D3:FE:61:5E,9.1,1.3,95.2,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:22
2,9C:C7:D3:FE:61:5E,1.8,1.3,95.2,10.13,1.86,18.4,0.16,0.24,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:32
3,9C:C7:D3:FE:61:5E,5.9,1.3,94.6,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:36
4,9C:C7:D3:FE:61:5E,23.7,1.3,54.6,6.75,0.00,0.0,0.00,0.00,0.0,0.0,339.38,0.0,0.0,2026-09-20 09:45:40
5,9C:C7:D3:FE:61:5E,12.7,1.3,68.8,6.75,0.12,1.7,0.00,570.43,0.0,0.0,339.18,0.0,0.0,2026-09-20 12:19:07
6,9C:C7:D3:FE:61:5E,8.5,1.3,68.7,6.75,0.12,1.7,0.08,0.14,0.0,0.0,339.18,0.0,0.0,2026-09-20 12:19:17
7,9C:C7:D3:FE:61:5E,4.3,1.3,68.4,6.75,0.12,1.7,0.05,0.08,0.0,0.0,339.18,0.0,0.0,2026-09-20 12:19:27
8,9C:C7:D3:FE:61:5E,3.1,1.3,68.5,6.75,0.11,1.7,0.03,0.02,0.0,0.0,339.18,0.0,0.0,2026-09-20 12:19:37
9,9C:C7:D3:FE:61:5E,2.5,1.3,67.9,6.75,0.12,1.8,0.02,0.02,0.0,0.0,339.18,0.0,0.0,2026-09-20 12:19:47

In [29]:
print(df_metricas_analisadas["cpu_percent"].mean())
display(df_metricas_analisadas["cpu_percent"])
print(df_metricas_analisadas["cpu_percent"].max())

cpu_alta = df_metricas_analisadas[df_metricas_analisadas["ram_percent"] > 95.0]
display(cpu_alta)

display(cpu_alta["timestamp"].dt.day_name())
#as duas no sabado

9.309999999999999

0    21.5
1     9.1
2     1.8
3     5.9
4    23.7
5    12.7
6     8.5
7     4.3
8     3.1
9     2.5
Name: cpu_percent, dtype: float64

23.7

,user,cpu_percent,cpu_frequency,ram_percent,swap_memory_total,swap_memory_used,swap_memory_percent,upload_speed,download_speed,temperature,fans_speed,disk,gpu_usage,gpu_energy,timestamp
1,9C:C7:D3:FE:61:5E,9.1,1.3,95.2,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:22
2,9C:C7:D3:FE:61:5E,1.8,1.3,95.2,10.13,1.86,18.4,0.16,0.24,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:32

1    Saturday
2    Saturday
Name: timestamp, dtype: str

In [30]:
#media por dia da semana
media_cpu_por_dia = df_metricas_analisadas.groupby(df_metricas_analisadas["timestamp"].dt.day_name())["cpu_percent"].mean()

display(media_cpu_por_dia)

dados_do_sabado = df_metricas_analisadas[df_metricas_analisadas["timestamp"].dt.weekday == 5]

print("media sabado")
print(dados_do_sabado["cpu_percent"].mean())

timestamp
Saturday    9.575000
Sunday      9.133333
Name: cpu_percent, dtype: float64

media sabado
9.575

In [54]:
ultima = df_metricas_analisadas["timestamp"].max()
primeira = df_metricas_analisadas["timestamp"].min()
uma_hora = df_metricas_analisadas[df_metricas_analisadas["timestamp"] >= (ultima - pd.Timedelta(hours=1))]
um_dia = df_metricas_analisadas[df_metricas_analisadas["timestamp"] >= (ultima - pd.Timedelta(hours=24))]

df_media_ultima_hora = uma_hora.groupby([uma_hora["timestamp"].dt.floor('h'), "user"]).mean()
df_media_ultimo_dia = um_dia.groupby([um_dia["timestamp"].dt.floor('h'), "user"]).mean()
df_media_geral = df_metricas_analisadas.groupby("user").mean()

display(df_media_ultima_hora)
display(df_media_ultimo_dia)
display(df_media_geral)

,,cpu_percent,cpu_frequency,ram_percent,swap_memory_total,swap_memory_used,swap_memory_percent,upload_speed,download_speed,temperature,fans_speed,disk,gpu_usage,gpu_energy,timestamp,intervalo
timestamp,user,,,,,,,,,,,,,,,
2026-09-20 12:00:00,9C:C7:D3:FE:61:5E,6.22,1.3,68.46,6.75,0.118,1.72,0.036,114.138,0.0,0.0,339.18,0.0,0.0,2026-09-20 12:19:27,0 days 00:30:49.400000

,,cpu_percent,cpu_frequency,ram_percent,swap_memory_total,swap_memory_used,swap_memory_percent,upload_speed,download_speed,temperature,fans_speed,disk,gpu_usage,gpu_energy,timestamp,intervalo
timestamp,user,,,,,,,,,,,,,,,
2026-09-19 18:00:00,9C:C7:D3:FE:61:5E,9.575,1.3,94.925,10.13,1.860,18.40,0.040,0.060,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:15.750,0 days 00:00:21
2026-09-20 09:00:00,9C:C7:D3:FE:61:5E,23.700,1.3,54.600,6.75,0.000,0.00,0.000,0.000,0.0,0.0,339.38,0.0,0.0,2026-09-20 09:45:40.000,0 days 15:02:04
2026-09-20 12:00:00,9C:C7:D3:FE:61:5E,6.220,1.3,68.460,6.75,0.118,1.72,0.036,114.138,0.0,0.0,339.18,0.0,0.0,2026-09-20 12:19:27.000,0 days 00:30:49.400000

,cpu_percent,cpu_frequency,ram_percent,swap_memory_total,swap_memory_used,swap_memory_percent,upload_speed,download_speed,temperature,fans_speed,disk,gpu_usage,gpu_energy,timestamp,intervalo
user,,,,,,,,,,,,,,,
9C:C7:D3:FE:61:5E,9.31,1.3,77.66,8.102,0.803,8.22,0.034,57.093,0.0,0.0,336.624,0.0,0.0,2026-09-20 05:01:35.800,0 days 01:57:28.222222

In [ ]:
df_metricas_analisadas["intervalo"] = df_metricas_analisadas["timestamp"].diff()
display(df_metricas_analisadas)

paradas = df_metricas_analisadas[df_metricas_analisadas["intervalo"] > pd.Timedelta(minutes=5)]


#mostra em um df, quais linhas que tiveram essa parada
display(paradas)

,user,cpu_percent,cpu_frequency,ram_percent,swap_memory_total,swap_memory_used,swap_memory_percent,upload_speed,download_speed,temperature,fans_speed,disk,gpu_usage,gpu_energy,timestamp,intervalo
0,9C:C7:D3:FE:61:5E,21.5,1.3,94.7,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:42:33,NaT
1,9C:C7:D3:FE:61:5E,9.1,1.3,95.2,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:22,0 days 00:00:49
2,9C:C7:D3:FE:61:5E,1.8,1.3,95.2,10.13,1.86,18.4,0.16,0.24,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:32,0 days 00:00:10
3,9C:C7:D3:FE:61:5E,5.9,1.3,94.6,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:36,0 days 00:00:04
4,9C:C7:D3:FE:61:5E,23.7,1.3,54.6,6.75,0.00,0.0,0.00,0.00,0.0,0.0,339.38,0.0,0.0,2026-09-20 09:45:40,0 days 15:02:04
5,9C:C7:D3:FE:61:5E,12.7,1.3,68.8,6.75,0.12,1.7,0.00,570.43,0.0,0.0,339.18,0.0,0.0,2026-09-20 12:19:07,0 days 02:33:27
6,9C:C7:D3:FE:61:5E,8.5,1.3,68.7,6.75,0.12,1.7,0.08,0.14,0.0,0.0,339.18,0.0,0.0,2026-09-20 12:19:17,0 days 00:00:10
7,9C:C7:D3:FE:61:5E,4.3,1.3,68.4,6.75,0.12,1.7,0.05,0.08,0.0,0.0,339.18,0.0,0.0,2026-09-20 12:19:27,0 days 00:00:10
8,9C:C7:D3:FE:61:5E,3.1,1.3,68.5,6.75,0.11,1.7,0.03,0.02,0.0,0.0,339.18,0.0,0.0,2026-09-20 12:19:37,0 days 00:00:10
9,9C:C7:D3:FE:61:5E,2.5,1.3,67.9,6.75,0.12,1.8,0.02,0.02,0.0,0.0,339.18,0.0,0.0,2026-09-20 12:19:47,0 days 00:00:10

,user,cpu_percent,cpu_frequency,ram_percent,swap_memory_total,swap_memory_used,swap_memory_percent,upload_speed,download_speed,temperature,fans_speed,disk,gpu_usage,gpu_energy,timestamp,intervalo
4,9C:C7:D3:FE:61:5E,23.7,1.3,54.6,6.75,0.00,0.0,0.0,0.00,0.0,0.0,339.38,0.0,0.0,2026-09-20 09:45:40,0 days 15:02:04
5,9C:C7:D3:FE:61:5E,12.7,1.3,68.8,6.75,0.12,1.7,0.0,570.43,0.0,0.0,339.18,0.0,0.0,2026-09-20 12:19:07,0 days 02:33:27

In [43]:
df_p95_por_hora = df_metricas_analisadas.groupby(
    [df_metricas_analisadas["timestamp"].dt.floor('h'), "user"])[["cpu_percent", "cpu_frequency", "ram_percent", "swap_memory_percent","gpu_usage", "gpu_energy", "temperature", "fans_speed","upload_speed", "download_speed", "disk"]].quantile(0.95)

display(df_p95_por_hora)

df_p95_geral = df_metricas_analisadas.groupby("user")[["cpu_percent", "cpu_frequency", "ram_percent", "swap_memory_percent","gpu_usage", "gpu_energy", "temperature", "fans_speed","upload_speed", "download_speed", "disk"]].quantile(0.95)

display(df_p95_geral)

df_p95_ultima_hora = uma_hora.groupby("user")[["cpu_percent", "cpu_frequency", "ram_percent", "swap_memory_percent","gpu_usage", "gpu_energy", "temperature", "fans_speed","upload_speed", "download_speed", "disk"]].quantile(0.95)
df_p95_ultima_hora["timestamp"] = ultima.floor('h')

display(df_p95_ultima_hora)

,,cpu_percent,cpu_frequency,ram_percent,swap_memory_percent,gpu_usage,gpu_energy,temperature,fans_speed,upload_speed,download_speed,disk
timestamp,user,,,,,,,,,,,
2026-09-19 18:00:00,9C:C7:D3:FE:61:5E,19.64,1.3,95.20,18.40,0.0,0.0,0.0,0.0,0.136,0.204,332.74
2026-09-20 09:00:00,9C:C7:D3:FE:61:5E,23.70,1.3,54.60,0.00,0.0,0.0,0.0,0.0,0.000,0.000,339.38
2026-09-20 12:00:00,9C:C7:D3:FE:61:5E,11.86,1.3,68.78,1.78,0.0,0.0,0.0,0.0,0.074,456.372,339.18

,cpu_percent,cpu_frequency,ram_percent,swap_memory_percent,gpu_usage,gpu_energy,temperature,fans_speed,upload_speed,download_speed,disk
user,,,,,,,,,,,
9C:C7:D3:FE:61:5E,22.71,1.3,95.2,18.4,0.0,0.0,0.0,0.0,0.124,313.8445,339.29

,cpu_percent,cpu_frequency,ram_percent,swap_memory_percent,gpu_usage,gpu_energy,temperature,fans_speed,upload_speed,download_speed,disk,timestamp
user,,,,,,,,,,,,
9C:C7:D3:FE:61:5E,11.86,1.3,68.78,1.78,0.0,0.0,0.0,0.0,0.074,456.372,339.18,2026-09-20 12:00:00

In [ ]:
tempo_fora = paradas["intervalo"].sum()

print(tempo_fora)
print(tempo_fora.total_seconds())
minutos_fora = round(tempo_fora.total_seconds() / 60, 1)
minutos_total = (ultima - primeira).total_seconds() / 60
minutos_ligada = minutos_total - minutos_fora  
print(minutos_fora)
#estimativa?
lucro_min = 0.009
gasto_min_ligada = 0.003
perda = (minutos_fora * lucro_min) - (gasto_min_ligada * minutos_fora)
print(perda)


pct_fora = 100 * minutos_fora / minutos_total       
pct_ligada = 100 * minutos_ligada / minutos_total

print(pct_fora)
print(pct_ligada)

0 days 17:35:31
63331.0
1055.5
6.332999999999999
99.83605006778699
0.16394993221301024