In [1]:
import pandas as pd

df_metricas = pd.read_csv("data.csv", delimiter= ";", encoding="utf-8")
display(df_metricas)

,user,cpu_percent,cpu_frequency,ram_percent,swap_memory_total,swap_memory_used,swap_memory_percent,upload_speed,download_speed,temperature,fans_speed,disk,gpu_usage,gpu_energy,timestamp
0,9c:c7:d3:fe:61:5e,21.5,1.3,94.7,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:42:33.308688
1,9c:c7:d3:fe:61:5e,9.1,1.3,95.2,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:22.218620
2,9c:c7:d3:fe:61:5e,1.8,1.3,95.2,10.13,1.86,18.4,0.16,0.24,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:32.258389
3,9c:c7:d3:fe:61:5e,5.9,1.3,94.6,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:36.987173

In [3]:
display(df_metricas.info())
#pegar dados (ver informações dos mesmos)

print(list(df_metricas.columns))

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   user                 4 non-null      str
 1   cpu_percent          4 non-null      float64
 2   cpu_frequency        4 non-null      float64
 3   ram_percent          4 non-null      float64
 4   swap_memory_total    4 non-null      float64
 5   swap_memory_used     4 non-null      float64
 6   swap_memory_percent  4 non-null      float64
 7   upload_speed         4 non-null      float64
 8   download_speed       4 non-null      float64
 9   temperature          4 non-null      float64
 10  fans_speed           4 non-null      float64
 11  disk                 4 non-null      float64
 12  gpu_usage            4 non-null      float64
 13  gpu_energy           4 non-null      float64
 14  timestamp            4 non-null      str
dtypes: float64(13), str(2)
memory usage: 612.0 bytes

None

['user', 'cpu_percent', 'cpu_frequency', 'ram_percent', 'swap_memory_total', 'swap_memory_used', 'swap_memory_percent', 'upload_speed', 'download_speed', 'temperature', 'fans_speed', 'disk', 'gpu_usage', 'gpu_energy', 'timestamp']

In [6]:
print(df_metricas["cpu_frequency"])

df_metricas_analisadas = df_metricas

df_metricas_analisadas["timestamp"] = pd.to_datetime(df_metricas_analisadas["timestamp"], format="%Y-%m-%d %H:%M:%S.%f")

0    1.3
1    1.3
2    1.3
3    1.3
Name: cpu_frequency, dtype: float64

In [11]:
df_metricas_analisadas["timestamp"].info()
#agora ta datetime

df_metricas_analisadas["user"] = df_metricas_analisadas["user"].str.upper()
df_metricas_analisadas["user"]

df_metricas_analisadas = df_metricas_analisadas.drop_duplicates(subset=["timestamp"], keep="first")

df_metricas_analisadas["timestamp"] = df_metricas_analisadas["timestamp"].dt.floor('s')

df_metricas_analisadas = df_metricas_analisadas.fillna(0)

display(df_metricas_analisadas)

<class 'pandas.Series'>
RangeIndex: 4 entries, 0 to 3
Series name: timestamp
Non-Null Count  Dtype
--------------  -----
4 non-null      datetime64[us]
dtypes: datetime64[us](1)
memory usage: 164.0 bytes

,user,cpu_percent,cpu_frequency,ram_percent,swap_memory_total,swap_memory_used,swap_memory_percent,upload_speed,download_speed,temperature,fans_speed,disk,gpu_usage,gpu_energy,timestamp
0,9C:C7:D3:FE:61:5E,21.5,1.3,94.7,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:42:33
1,9C:C7:D3:FE:61:5E,9.1,1.3,95.2,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:22
2,9C:C7:D3:FE:61:5E,1.8,1.3,95.2,10.13,1.86,18.4,0.16,0.24,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:32
3,9C:C7:D3:FE:61:5E,5.9,1.3,94.6,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:36

In [12]:
display(df_metricas_analisadas)

,user,cpu_percent,cpu_frequency,ram_percent,swap_memory_total,swap_memory_used,swap_memory_percent,upload_speed,download_speed,temperature,fans_speed,disk,gpu_usage,gpu_energy,timestamp
0,9C:C7:D3:FE:61:5E,21.5,1.3,94.7,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:42:33
1,9C:C7:D3:FE:61:5E,9.1,1.3,95.2,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:22
2,9C:C7:D3:FE:61:5E,1.8,1.3,95.2,10.13,1.86,18.4,0.16,0.24,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:32
3,9C:C7:D3:FE:61:5E,5.9,1.3,94.6,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:36

In [ ]:
print(df_metricas_analisadas["cpu_percent"].mean())
display(df_metricas_analisadas["cpu_percent"])
print(df_metricas_analisadas["cpu_percent"].max())

cpu_alta = df_metricas_analisadas[df_metricas_analisadas["ram_percent"] > 95.0]
display(cpu_alta)

display(cpu_alta["timestamp"].dt.day_name())
#as duas no sabado

9.575

0    21.5
1     9.1
2     1.8
3     5.9
Name: cpu_percent, dtype: float64

21.5

,user,cpu_percent,cpu_frequency,ram_percent,swap_memory_total,swap_memory_used,swap_memory_percent,upload_speed,download_speed,temperature,fans_speed,disk,gpu_usage,gpu_energy,timestamp
1,9C:C7:D3:FE:61:5E,9.1,1.3,95.2,10.13,1.86,18.4,0.00,0.00,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:22
2,9C:C7:D3:FE:61:5E,1.8,1.3,95.2,10.13,1.86,18.4,0.16,0.24,0.0,0.0,332.74,0.0,0.0,2026-09-19 18:43:32

1    Saturday
2    Saturday
Name: timestamp, dtype: str

In [30]:
media_cpu_por_dia = df_metricas_analisadas.groupby(df_metricas_analisadas["timestamp"].dt.day_name())["cpu_percent"].mean()

display(media_cpu_por_dia)

dados_do_sabado = df_metricas_analisadas[df_metricas_analisadas["timestamp"].dt.weekday == 5]

print("media sabado")
print(dados_do_sabado["cpu_percent"].mean())

timestamp
Saturday    9.575
Name: cpu_percent, dtype: float64

media sabado
9.575